# Report best regression model


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import Ridge, LinearRegression
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import Lasso
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [ ]:
x=np.arange(0, 30).reshape((-1, 1))
y=np.array([3,4,5,7,10,8,9,10,10,23,27,44,50,63,67,60,62,70,75,88,81,87,95,100,108,135,151,160,169,179])
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=1)

LINEAR REGRESSION MODEL

In [ ]:
lr=LinearRegression()
lr.fit(x_train, y_train)
lr.intercept_, lr.coef_

(-20.606770975303952, array([6.07381562]))

In [ ]:
y_pred_lr=lr.predict(x_test)
y_pred_lr

array([ 82.64809464, 106.94335714,  40.13138527,  94.79572589,
        64.42664777, 100.86954151, 137.31243526,  -2.3853241 ,
       125.16480401])

STOCHASTIC GRADIENT DESCENT REGRESSOR

In [ ]:
sgdr=SGDRegressor(max_iter=1000, penalty=None, eta0=0.05)
sgdr.fit(x, y.ravel())
sgdr.intercept_, sgdr.coef_

(array([5.78956218e+10]), array([-1.74086703e+11]))

In [ ]:
y_pred_sgdr=sgdr.predict(x_test)
y_pred_sgdr

array([-2.90157833e+12, -3.59792514e+12, -1.68297141e+12, -3.24975173e+12,
       -2.37931822e+12, -3.42383844e+12, -4.46835866e+12, -4.64364487e+11,
       -4.12018525e+12])

POLYNOMIAL REGRESSION

In [ ]:
print(pd.DataFrame(x).head())
print(x.shape)
print(x_train.shape)
print(x_test.shape)

   0
0  0
1  1
2  2
3  3
4  4
(30, 1)
(21, 1)
(9, 1)


In [ ]:
pr=PolynomialFeatures(degree=3)
x_train2=pr.fit_transform(x_train)
x_test2=pr.fit_transform(x_test)

In [ ]:
pr_clf=LinearRegression()
pr_clf.fit(x_train2, y_train)
y_pred_pr=pr_clf.predict(x_test2)
pr_clf.score(x_test2, y_test)

0.9429701193890685

RIDGE REGRESSION

In [ ]:
rr=Ridge(alpha=1)
rr.fit(x_train, y_train)
y_pred_rr=rr.predict(x_test)
rr_poly=Ridge(alpha=1)
rr_poly.fit(x_train2, y_train)
y_pred_rr-rr_poly.predict(x_test2)

array([14.6175609 ,  9.64959812,  9.39363191, 12.95208393, 14.3249221 ,
       11.51342533, -6.60414196, -8.86451536,  1.34794053])

In [ ]:
print(format(rr.score(x_test, y_test)))
print(np.sum(rr.coef_!=0))
print(format(rr_poly.score(x_test2, y_test)))
print(np.sum(rr_poly.coef_ !=0))

0.8772755852384372
1
0.942560354097709
3


LASSO REGRESSION

In [ ]:
lasso=Lasso(alpha=0.1)
lasso.fit(x_train, y_train)
y_pred_lasso=lasso.predict(x_test)

In [ ]:
print(lasso.score(x_train, y_train))
print(lasso.score(x_test, y_test))
print(np.sum(lasso.coef_!=0))

0.9386339164856258
0.8771390203142125
1


In [ ]:
print(np.sqrt(mean_squared_error(y_test, y_pred_lr)), 
      np.sqrt(mean_squared_error(y_test, y_pred_sgdr)), 
      np.sqrt(mean_squared_error(y_test, y_pred_pr)), 
      np.sqrt(mean_squared_error(y_test, y_pred_rr)), 
      np.sqrt(mean_squared_error(y_test, y_pred_lasso)))

13.93561391604153 3149940316541.277 9.491665911106898 13.92376539468306 13.931510264674847


In [ ]:
print(r2_score(y_test, y_pred_lr), 
      r2_score(y_test, y_pred_sgdr), 
      r2_score(y_test, y_pred_pr), 
      r2_score(y_test, y_pred_rr), 
      r2_score(y_test, y_pred_lasso))

0.8770666300459948 -6.28090501429801e+21 0.9429701193890685 0.8772755852384372 0.8771390203142125


Hence it can be concluded that the best regression model for the given dataset is the Polynomial Regression Model.