## <center> ACM India and RBCDSAI Joint Summer School on DS/AI/ML
### <center> Hands-on Tutorial Day-1 
### <center> Python for DS/AI/ML

<h1> Contents: </h1>
1. Assignment of variables  <br />
2. Operators <br />
3. Lists, tuples, sets and dictionaries <br />
4. Loops <br />
5. Defining a function <br />
6. Package usage <br />

### Assignment of variables 

In [ ]:
# assigning variable names using '='
a = 10
b = 15
c = 5.5 

In [ ]:
type(a)

int

**print()** --> Displays the value of variable 

In [ ]:
# Displaying value of a+b and c*b
print('Sum of a and b is', a+b) 
print('Product of c and b is', c*b)

Sum of a and b is 25
Product of c and b is 82.5


**str()** --> to change the variable to a string <br />
**int()** --> to change the variable to an integer; convert floating point numbers/strings to integers <br />
**float()** --> to change the variable to a floating point number <br />
**type()** --> to check the datatype/object type <br />

In [ ]:
# Change the datatype
a = str(a) # to a string
b = float(b) # to a float
c = int(c) # to a integer

print('The values of a_str,b_float,c_int are', a, b, c,'respectively')
print('variable type:', type(a),type(b),type(c))

The values of a_str,b_float,c_int are 10 15.0 5 respectively
variable type: <class 'str'> <class 'float'> <class 'int'>


**Exercise questions:**

Create a variable x, obtain the user input for x and report the type of variable x

### Sequences
Strings, lists and tuples are sequences. They can be indexed and sliced in the same way.

Tuples and strings are “immutable” (which basically means we can’t change individual elements within the tuple, and we cannot change individual characters within a string) whereas lists are “mutable” (.i.e we can change elements in a list.)

Sequences share the following operations

- a[i] returns i-th element of a
- a[i:j] returns elements i up to j-1
- len(a) returns number of elements in sequence
- min(a) returns smallest value in sequence
- max(a) returns largest value in sequence
- x in a returns True if x is element in a
- a + b concatenates a and b
n * a creates n copies of sequence a

In [ ]:
# Concatenation of strings
s1 = 'Hello '
s2 = 'World'
s3 = s1+s2
print(s3)
print(s3.split( ))

Hello World
['Hello', 'World']


**Exercise questions**

a. Print a sentence of your name and college from a separate variables *name* and *college* 

b. Report the length of your name 


### Lists


In [ ]:
# creating a list
list_1 = ['Welcome', 'Everyone', ('Welcome','To'),  [ 'Summer ', 'School']] # creating a list using square_brackets
print(list_1)

['Welcome', 'Everyone', ('Welcome', 'To'), ['Summer ', 'School']]


In [ ]:
# mutablility of the list --> values inside a list can be mutated/changed
list_1[0] = 'Hello' # in python indexing begins with 0 instead of 1
list_1[-1] = 'Course' # -1 refers to last element of the list
print('The mutated list',list_1) 
print('first two items of the list',list_1[0:2]) 

The mutated list ['Hello', 'Everyone', ('Welcome', 'To'), 'Course']
first two items of the list ['Hello', 'Everyone']


In [ ]:
# Iteratability of the list
for i in list_1:
    print(i)

Hello
Everyone
('Welcome', 'To')
Course


#### Useful functions for a list
**.append(i)** --> adds an element i in the list <br />
**.extend(lst)** --> expands the list by including another list lst <br />
**.insert(i,j)** --> inserts a new element j in specified index i <br />
**.sort()** --> sorts the list <br />
**.remove(i)** --> removes the element i in the list <br />

In [ ]:
# Creating list using range()
x = list(range(5))
print(x)

[0, 1, 2, 3, 4]


In [ ]:
x.append(10)
print(x)

In [ ]:
x.remove(3)
print(x)

[0, 1, 2, 4, 10]


In [ ]:
# range() creates a sequence from 0 to n-1 
# and frequently used for loops.
for i in range(4):
    print(i ** 2)

0
1
4
9


**Exercise questions**

Create a list with your favourites in the order of number, fruit, subject and sweet and print only the favorite fruit and subject

### Operators
1. Arithmetic operators: +, -, *, /, **, //, %
2. Boolean Expressions: returns True or False 
3. Relational operators:  ==, <=, <, >, >=, !=
4. Logical Operators: and, or, not

In [ ]:
# Relational operators
r1 = 3 == 9/3
print(r1)
r2 = -3 >= -2
print(r2)

True
False


In [ ]:
# Boolean operators
r3 = r1 and r2
r4 = r1 or r2
r5 = not r1
print('Values of r3:%r, r4:%r, r5:%r'%(r3, r4, r5))

Values of r3:False, r4:True, r5:False


In [ ]:
# Arithmetic operators
var1, var2 = 6, 10
print(var1+var2)    # Addition 
print(var1 - var2)  # Subtraction
print(var1 * var2)  # Multiplication
print(var1 / var2)  # Division
print(var1 % var2)  # Modulus

16
-4
60
0.6
6


**Exercise question:**

Check whether the following questions are true or false

a. 2.5 == 5/2  
b. 22/7 == 3.14  

### Tuples
    A tuple is a (immutable) sequence of objects and the objects in the sequence can be of nay data type.

In [ ]:
# Creating a tuple object
t1 = ('One',2,'Three',[4.0])
t1

('One', 2, 'Three', [4.0])

In [ ]:
#Immutability of tuple
t1[2] =3

TypeError: ignored

In [ ]:
# iteratability of tuple
for i in t1:
    print(i)

One
2
Three
[4.0]


### Set

In [ ]:
set1 = {0,2,6,9,1,5,2,9,'a','abc'}
set1

{0, 1, 2, 5, 6, 9, 'a', 'abc'}

In [ ]:
set1 = {0,2,6,9,1,5,2,9,['a','abc']}
set1

TypeError: ignored

Note that set cannot store list in it (throws an error) and they cannot have duplicate items (it automatically removes '9' repeated twice). Also, the order is lost in a set.

In [ ]:
# iteratability of set
for i in set1:
    print(i)

0
1
2
5
6
9
a
abc


In [ ]:
set1[4] = 1

TypeError: ignored

In [ ]:
# Set is mutable but not using indices
set1.remove(5)
print(set1)
set1.add(11)
print(set1)

{0, 1, 2, 6, 9, 'a', 'abc'}
{0, 1, 2, 6, 9, 11, 'a', 'abc'}


### Dictionary
   Dictionaries are also called “associative arrays” and “hash tables”. Dictionaries are unordered sets of key-value pairs.

In [ ]:
# Creating a dictionary
temp1 = {'Today' : '22 deg C', 'Yesterday' : '24 deg C'}
temp2 = dict( Tomorrow = 'Unknown')

In [ ]:
temp1

{'Today': '22 deg C', 'Yesterday': '24 deg C'}

In [ ]:
temp2

{'Tomorrow': 'Unknown'}

In [ ]:
# Mutability
print(temp1['Today'])
temp1['Today'] = '23 deg C'
print(temp1.get('Today'))

22 deg C
23 deg C


In [ ]:
# iteratability of a dictionary
for key in temp1:
    print('The key is',key,'and the value is', temp1[key])

The key is Today and the value is 23 deg C
The key is Yesterday and the value is 24 deg C


In [ ]:
'Today' in temp1

True

In [ ]:
### Indexing Sequence

In [ ]:
word_1 = 'Hello Everyone!!'
print(word_1[0])

In [ ]:
print(word_1[-3])

In [ ]:
### Slicing sequence

In [ ]:
word_2 = word_1[0:5]
word_2

In [ ]:
print(word_1[:-2])

### Loops
 
 - Loops are helpful to iterate a set of statements 
 - Three different loops discussed:
    - For loop
    - While loop
    - if-else loop


#### For loop
  To iterate a set of statements for a specific number of times (Based on the sequence)

In [ ]:
# Iterate using the range
n = 4
for i in range(0, n):
    print(i)

0
1
2
3


In [ ]:
# Iterate using the variable
a = 'python'
for i in a:
	print(i)

p
y
t
h
o
n


#### While loop
The statement will be executed until the condition is true

In [ ]:
count = 0
while count <= 5:
  print('hello')
  count=count+1

hello
hello
hello
hello
hello
hello


#### if-else statement
Based on the condition, the jobs will be executed

In [ ]:
a = int(input('Enter a value'))
if a % 2 == 0:
  print("Even number")
else:
  print("Odd number")

Enter a value15
Odd number


**Exercise questions**

Write a code to check whether the year obtained is leap year or not

### Defining a function

In [ ]:
# Function to add two numbers
def add_numbers(x, y):
    return x + y

In [ ]:
# Calling a function
add_numbers(1, 2)

3

In [ ]:
def add_numbers2(x, y):
    print(x + y)

In [ ]:
add_numbers2(1, 2)

3


In [ ]:
z1 = add_numbers
z1(2,2)

**Exercise questions**

Write a function using the above code to print whether the given year is leap or not

### Package usage

In [ ]:
# importing the package numpy
import numpy as np

In [ ]:
print(np.array([0,1,2])) # printing an array created using numpy package
print(np.eye(3)) # Creates an identity mtrix

In [ ]:
x = np.array([0,1,2])
y = np.array([5,2,6])

print(x+y)    # elementwise Addition
print(x-y)    # elementwise Subtraction
print(x*y)    # elementwise Multiplication
print(x/y)    # elementwise Division
print(x.dot(y))    # dot product

[5 3 8]
[-5 -1 -4]
[ 0  2 12]
[0.         0.5        0.33333333]
14


In [ ]:
# importing only a variable from a package
from math import pi

In [ ]:
print(pi)

3.141592653589793


**Exercise question:**

Generate a numeric array of 4 elements and identify the sum of squares of the element